name: Build and Deploy

on:
  push:
    branches:
      - main  # またはデプロイしたいブランチ名

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Rust setup
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    # wasm-pack をインストール
    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.3.0

    # wasm-packを使用してWASMをビルド
    - name: Build wasm
      run: |
        cd wasm
        wasm-pack build --target web

    # Reactのビルド
    - name: Build React project
      run: |
        npm install
        npm run build
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # dist フォルダーのアップロード
        path: './dist'

    # ビルドしたファイルをgh-pagesブランチにデプロイ
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        github_token: ${{ secrets.QUART_APP }}

